### ISSUE TITLE
你好，可以支持maven集成吗

### ISSUE THREAD

**Issue by duanxifeng** [YeDaxia/JApiDocs#1]
可以支持maven集成吗

**Comment by YeDaxia** [comment]
就是用maven仓库的：http://search.maven.org/#artifactdetails%7Cio.github.yedaxia%7Cjapidocs%7C1.0%7Cjar
不过发布到 rap 的功能还没发布到 maven 仓库，等稳定一些再发，你可以先用工程里面的 jar 包。

**Comment by duanxifeng** [comment]
好的，谢谢，不过文档里只写了gradle的集成
