### ISSUE TITLE
io.github.yedaxia.apidocs.ParseUtils#searchJavaFileInner 递归查找名称为 Object 会报错，没有过滤 Object

### ISSUE THREAD

**Issue by zengyufei** [YeDaxia/JApiDocs#11]
![snipaste_2018-04-09_15-14-57](https://user-images.githubusercontent.com/13251679/38484328-ceb948ce-3c08-11e8-843b-653abf86077c.png)

**Comment by YeDaxia** [comment]
无法处理的类已经默认Object处理
