### ISSUE TITLE
多模块的项目,目前无法读取.jar中的文件

### ISSUE THREAD

**Issue by sudot** [YeDaxia/JApiDocs#23]
一个多模块的项目
Controller和响应的DTO不在同一个模块,是通过引入.jar的方式注入依赖
然后使用@ApiDoc(jar文件中的类.class),就会找不到这个类

**Comment by hxy91819** [comment]
我也遇到了这个问题，目前只能临时拷贝DTO到web工程里。
如果有公开源码，可以考虑加一个dto目录的配置选项。

**Comment by YeDaxia** [comment]
JApidocs 是通过解析 java 源代码构建语法树来读取到相关信息的，所以对于 jar 包里面的 class ，目前是读不到的。 @hxy91819 提到的源码关联是个思路～ 我先看看这个应该怎么做，也欢迎提 PR 啊～

**Comment by YeDaxia** [comment]
1.4.1 在没有源码的情况下，支持反射的方式读取javabean~
