### ISSUE TITLE
在t-io http 项目中生成 获取不到访问地址

### ISSUE THREAD

**Issue by sinper0212** [YeDaxia/JApiDocs#28]
url: ${APIURL}  

import org.tio.http.server.annotation.RequestPath;
/**
     * 用户列表(带分页)
     *
     * @param start
     * @param size
     * @param request
     * @return
     */
    @ApiDoc(TUser[].class)
    @RequestPath(value = "/userList/{start}/{size}")

**Comment by YeDaxia** [comment]
没有支持 t-io ，url需要在@ApiDoc 中指定

```
@Apidoc(result = TUser[].class, url ="/userList/{start}/{size}")
```
