### ISSUE TITLE
返回值是泛型ApiDoc注解应该怎么写?

### ISSUE THREAD

**Issue by GavinAndre** [YeDaxia/JApiDocs#3]
比如一个登录接口,请求参数是用户名和密码
```
     /**
     * 用户登录
     *
     * @param username 用户名
     * @param password 密码
     * @return
     */
    @ApiDoc(???.class)
    @RequestMapping(value = "login.do", method = RequestMethod.POST) // 匹配接口路径和请求方式
    @ResponseBody // 自动将返回值序列化成json
    public ServerResponse<User> login(String username, String password, HttpSession session) {
        ServerResponse<User> response = iUserService.login(username, password);
        if (response.isSuccess()) {
            session.setAttribute(Const.CURRENT_USER, response.getData());
        }
        return response;
    }
```

ServerResponse<T>里有三个参数
```
    private int status;
    private String msg;
    private T data;
```

我想要的返回格式如下,当中data用的是泛型,填充User对象
```
{
    "status": 0,
    "data": {
        "id": 12,
        "username": "aaa",
        "email": "aaa@163.com",
        "phone": null,
        "role": 0,
        "createTime": 1479048325000,
        "updateTime": 1479048325000
    }
}
```

@ApiDoc(???.class)如果用User的话本地接口文档返回结果就是如下格式
{
        "id": 12,
        "username": "string",
        "email": "string",
        "phone": string,
        "role": 0,
        "createTime": string,
        "updateTime": string
}

但是同步到RAP后响应参数列表里,ServerResponse对象保留了,只是status变成了code,msg和data都保留了

  变量名 | 含义 | 类型 | 备注
-- | -- | -- | --
  code |   | number | @mock=0
  data |   | object |  
      answer |   | string | @mock=@STRING
      createTime |   | string | @mock=@DATETIME
      email |   | string | @mock=@STRING
      id |   | number | @mock=@INTEGER
      password |   | string | @mock=@STRING
      phone |   | string | @mock=@STRING
      question |   | string | @mock=@STRING
      role |   | number | @mock=@INTEGER
      updateTime |   | string | @mock=@DATETIME
      username |   | string | @mock=@STRING
  msg |   | string | @mock=success

还有一个问题就是有些接口返回值不需要data,我只想返回如下格式应该怎么写
```
{
    "status": 0,
    "message":"密码错误,登录失败"
}
```

**Comment by YeDaxia** [comment]
泛型在1.2版本可以支持了

**Comment by jliang981** [comment]
请问，返回参数是List<Map<String, Object>>这种，那么@ApiDoc里面的result应该怎么配置呢？

**Comment by YeDaxia** [comment]
@jliang981 不支持这种结构，可以考虑用一个对象来封装Map
