### ISSUE TITLE
疑似BUG：DTO如果有重名的（在不同的package里），有几率搜索到错误的DTO

### ISSUE THREAD

**Issue by hxy91819** [YeDaxia/JApiDocs#30]
在源码里定位到这个方法：`io.github.yedaxia.apidocs.ParseUtils.searchJavaFileInner(String, File, String)`

在import中搜索类的时候，是使用`endWith()`进行匹配：
```
Optional<ImportDeclaration> idOp = compilationUnit.getImports().stream()
                .filter(im -> im.getNameAsString().endsWith(className)).findFirst();
```

如果一个DTO名称是yyyDTO，另一个package里的DTO是xxxyyyDTO，那么这里可能会搜索到另一个不正确的DTO。

我现在是自己改成了
```
Optional<ImportDeclaration> idOp = compilationUnit.getImports().stream()
                .filter(im -> im.getNameAsString().endsWith("." + className)).findFirst();
```

能够解决我遇到的这个问题，但是无法根本解决不同package里有同名DTO的问题。

进一步修改方案，我觉得可能需要搜索下当前controller的import，定位到这个类的Qualified Name，然后再去做匹配。目前没有想到如何实现……

**Comment by YeDaxia** [comment]
> 在源码里定位到这个方法：`io.github.yedaxia.apidocs.ParseUtils.searchJavaFileInner(String, File, String)`
> 
> 在import中搜索类的时候，是使用`endWith()`进行匹配：
> 
> ```
> Optional<ImportDeclaration> idOp = compilationUnit.getImports().stream()
>                 .filter(im -> im.getNameAsString().endsWith(className)).findFirst();
> ```
> 如果一个DTO名称是yyyDTO，另一个package里的DTO是xxxyyyDTO，那么这里可能会搜索到另一个不正确的DTO。
> 
> 我现在是自己改成了
> 
> ```
> Optional<ImportDeclaration> idOp = compilationUnit.getImports().stream()
>                 .filter(im -> im.getNameAsString().endsWith("." + className)).findFirst();
> ```
> 能够解决我遇到的这个问题，但是无法根本解决不同package里有同名DTO的问题。
> 
> 进一步修改方案，我觉得可能需要搜索下当前controller的import，定位到这个类的Qualified Name，然后再去做匹配。目前没有想到如何实现……

嗯，回复晚了，同一个 Java 类中应该不会出现 import 完整同名类的情况，比如 java.util.List 和 
```
import java.awt.List;
import java.util.List;
```
否则通不过编译期，所以是不会出现你提出的情况的。

另外需要用到同名类，则需要带上包名，那就是下面的查找逻辑了。

所以你的答案是可以解决掉这个 bug 的！
