### ISSUE TITLE
请求参数和URL生成的问题

### ISSUE THREAD

**Issue by howsunyt** [YeDaxia/JApiDocs#32]
/**
	 * 获取增量feature列表
	 * @param page		请求页
	 * @param pagesize		每页大小
	 * @param updatetime	上次获取时间
	 * @param sorttype		排序方式，1位正序，其他为倒序
	 * @return
	 */
	@ApiDoc(result = PersonInfoListResponseAndroid.class, url="/fsdkfrservice/facetech/featureupload", method = "POST")
	@RequestMapping(value = "/featureupload", method = RequestMethod.POST)
	public @ResponseBody PersonInfoListResponseAndroid featureUpload(@RequestParam(name = "page", required = false, defaultValue = "1") int pageIndex,
			@RequestParam(name = "pagesize", required = false, defaultValue = "50") int pageSize,
			@RequestParam(name = "updatetime", required = false) String updateTime,
			@RequestParam(name = "sorttype", required = false, defaultValue = "1") int sortType)

**Comment by YeDaxia** [comment]
已修复 @ApiDoc 的 url 和 method 字段不支持
