### ISSUE TITLE
ParseUtils.isCollectionType(String) 判断是否是集合 如果 type类型为List<Demo1.Demo2>形式 会判断出错

### ISSUE THREAD

**Issue by jkoChen** [YeDaxia/JApiDocs#33]
public static boolean isCollectionType(String className){
        String[] cPaths = className.split("\\.");
        String genericType = cPaths[cPaths.length - 1];
        int genericLeftIndex = genericType.indexOf("<");
        String rawType = genericLeftIndex != -1 ? genericType.substring(0, genericLeftIndex) : genericType;
        String collectionClassName = "java.util."+rawType;
        try{
            Class collectionClass = Class.forName(collectionClassName);
            return Collection.class.isAssignableFrom(collectionClass);
        }catch (ClassNotFoundException e){
            return false;
        }
    }

**Comment by jkoChen** [comment]
这个bug 我修改了上述几行代码的属性得以解决。
另外我参考你的思路和我另一个朋友的想法 结合项目的实际 
 重新实现了一个功能 同时解决了 泛型传递的问题 （泛型传递问题 参考我朋友的解决方案）
可以放到  github上不 @YeDaxia

**Comment by YeDaxia** [comment]
@jkoChen 当然很欢迎啊~ 你可以提交个PR过来，这样可以帮助到其他人~

**Comment by jkoChen** [comment]
好的 谢谢
