### ISSUE TITLE
如果配置多个`javaSrcPath`，则`DocContext->controllerFiles` 会重复添加`controllerFile`

### ISSUE THREAD

**Issue by zmingchun** [YeDaxia/JApiDocs#34]
`
Docs.DocsConfig config = new Docs.DocsConfig();
        config.setProjectPath("D:\\gitzone\\wzone\\w_article");
        config.setDocsPath("D:\\gitzone\\\\wzone\\w_article\\document\\apidocs\\article");
        config.addJavaSrcPath("D:\\gitzone\\wzone\\w_article\\app\\");
        config.addJavaSrcPath("D:\\gitzone\\wzone\\w_common\\src\\main\\java\\");
        config.setMvcFramework("play");
        Docs.buildHtmlDocs(config);
`
如果有多个`javaSrcPath`，则`DocContext->controllerFiles` 会重复添加`controllerFile`。
PS: 
配置这里`ProjectPath` 和 `JavaSrcPath` 在找寻源码上是互斥的，如果改为兼容就好了，以`projectPath`找到的源码为主，找不到再去`javaSrcPath` 下寻找。

**Comment by YeDaxia** [comment]
好久没看这个项目了，`addJavaSrcPath`的存在是防止代码逻辑没有考虑到的找到Java源文件的情况，让用户手动去设置，尤其一些多module的情况，不过一般的gralde 和 maven 项目应该是可以正常工作的。

所以如果用户设置了Java源码的路径，那应该就不做代码上的判断了，源码实现如下：

```
if (config.getJavaSrcPaths().isEmpty()) {
            findOutJavaSrcPaths();
        } else {
            javaSrcPaths.addAll(config.getJavaSrcPaths());
        }
```
