### ISSUE TITLE
gradle 多模块找不到源码目录

### ISSUE THREAD

**Issue by rootzhongfengshan** [YeDaxia/JApiDocs#37]
你这个坑还是挺多的，项目多模块，settings.gradle是这样写的
include "core"
include 'multi-main'
include 'metric:metric-create'
include 'metric:metric-task'
include 'metric:project-config'
include 'metric:metric-common'
include 'project'
include 'project:project-api'
include 'project:project-impl'
include 'request-log'
include 'redisson'
include 'auth'
include 'auth:auth-redis'
include 'auth:auth-resource'
include 'auth:auth-server'
然后在配置io.github.yedaxia.apidocs.DocContext.findOutJavaSrcPaths(DocContext.java:78)的时候String javaSrcPath = findModuleSrcPath(new File(projectDir, moduleName));
这个就报了空指针异常，原因是项目路径metric:metric-create直接就以这个作为参数了，作者有空修一下么？

**Comment by YeDaxia** [comment]
谢谢反馈，麻烦你提供以下项目的目录结构？

另外你可以先试一下手动把源码目录配置进去：

```java
DocsConfig => addJavaSrcPath
```

**Comment by rootzhongfengshan** [comment]
![image](https://user-images.githubusercontent.com/17941334/84847632-2029bf80-b084-11ea-9870-8daa6a4e9721.png)
