### ISSUE TITLE
对于多模块项目 common项目里的 bean 找不到

### ISSUE THREAD

**Issue by flytothedream** [YeDaxia/JApiDocs#51]
addJavaSrcPath 用法是什么？
对于多模块项目，我的Bean在common项目里，子项目生成文档，是找不到common里的bean的

**Comment by YeDaxia** [comment]
apidoc.log 日志发一下？`addJavaSrcPath ` 是用于JApidocs在识别源码目录失败的时候，自己来添加源码目录用的。
