### ISSUE TITLE
无法解析泛型么

### ISSUE THREAD

**Issue by Yumore** [YeDaxia/JApiDocs#53]
我的返回的是实体类是BaseResponse<T> 然后报错：Exception in thread "main" io.github.yedaxia.apidocs.exception.JavaFileNotFoundException: Cannot find java file , in java file : 
实体类：
public class ApiResult<T> {

    @JsonProperty(value = "code")
    private int Code = 0;
    @JsonProperty(value = "msg")
    private String Msg = "";
    @JsonProperty(value = "data")
    private T Data;
}

**Comment by YeDaxia** [comment]
泛型是支持的，可以看 SpringDemo。这个错误通常是由于解析类不在源码中导致的。

**Comment by Yumore** [comment]
项目包结构如下
|-com.company.module
|-com.company.module.comtroller
|-com.company.module.entity
|-com.company.module.entity.request
|-com.company.module.entity.response

请问是只需要添加entity这一级的，还是需要把request和response这两个子包也配置

**Comment by zhangyq1011** [comment]
Exception in thread "main" java.lang.ClassCastException: com.github.javaparser.ast.type.WildcardType cannot be cast to com.github.javaparser.ast.type.ClassOrInterfaceType
报错。
Controler定义为：
![image](https://user-images.githubusercontent.com/7411134/86096849-68b29580-bae6-11ea-9c9b-3131515164d8.png)
Result.java定义如下：
![Uploading image.png…]()

**Comment by YeDaxia** [comment]
> 项目包结构如下
> |-com.company.module
> |-com.company.module.comtroller
> |-com.company.module.entity
> |-com.company.module.entity.request
> |-com.company.module.entity.response
> 
> 请问是只需要添加entity这一级的，还是需要把request和response这两个子包也配置

配置到项目根目录即可，不用配置包路径~

**Comment by coderxiao2015** [comment]
> 项目包结构如下
> |-com.company.module
> |-com.company.module.comtroller
> |-com.company.module.entity
> |-com.company.module.entity.request
> |-com.company.module.entity.response
> 
> 请问是只需要添加entity这一级的，还是需要把request和response这两个子包也配置



> 我的返回的是实体类是BaseResponse 然后报错：Exception in thread "main" io.github.yedaxia.apidocs.exception.JavaFileNotFoundException: Cannot find java file , in java file :
> 实体类：
> public class ApiResult {
> 
> ```
> @JsonProperty(value = "code")
> private int Code = 0;
> @JsonProperty(value = "msg")
> private String Msg = "";
> @JsonProperty(value = "data")
> private T Data;
> ```
> 
> }

你的问题解决了吗，我在作者说的springdemo 上没看到关于泛型的处理
