### ISSUE TITLE
在springboot中使用了自定义返回类型，但是提示无法找到该类型

### ISSUE THREAD

**Issue by xidianzyf** [YeDaxia/JApiDocs#56]
你好，我在使用过程中遇到了如题错误，我的项目目录为
![image](https://user-images.githubusercontent.com/43774564/85983578-510ddb00-ba1a-11ea-9255-01ab880851d1.png)
其中Test.java为
`

public class Test {
    public static void main(String[] args) {
        String rootPath = "/Users/zhangyifan/IdeaProjects/hitao/src/main/java/com/qingtai/hitao/";
        DocsConfig config = new DocsConfig();
        config.setProjectPath(rootPath);
        config.setProjectName("hitao");
        config.setApiVersion("V2.0");
        config.setDocsPath("/Users/zhangyifan/IdeaProjects/hitao/src/main/java/com/qingtai/hitao/apidoc/");
        config.addJavaSrcPath(rootPath + "advice/");
        config.addJavaSrcPath(rootPath + "config/");
        config.addJavaSrcPath(rootPath + "controller/");
        config.addJavaSrcPath(rootPath + "dao/");
        config.addJavaSrcPath(rootPath + "dto/");
        config.addJavaSrcPath(rootPath + "enums/");
        config.addJavaSrcPath(rootPath + "exception/");
        config.addJavaSrcPath(rootPath + "model/");
        config.addJavaSrcPath(rootPath + "provider/");
        config.addJavaSrcPath(rootPath + "service/");
        config.addJavaSrcPath(rootPath + "service/serviceimpl/");
        config.setAutoGenerate(Boolean.TRUE);
        Docs.buildHtmlDocs(config);
    }

}
`

但是我在运行时出现了错误
`
6月 29, 2020 3:04:05 下午 io.github.yedaxia.apidocs.LogUtils info
信息: info: find java src paths:  [/Users/zhangyifan/IdeaProjects/hitao/src/main/java/com/qingtai/hitao/advice/, /Users/zhangyifan/IdeaProjects/hitao/src/main/java/com/qingtai/hitao/config/, /Users/zhangyifan/IdeaProjects/hitao/src/main/java/com/qingtai/hitao/controller/, /Users/zhangyifan/IdeaProjects/hitao/src/main/java/com/qingtai/hitao/dao/, /Users/zhangyifan/IdeaProjects/hitao/src/main/java/com/qingtai/hitao/dto/, /Users/zhangyifan/IdeaProjects/hitao/src/main/java/com/qingtai/hitao/enums/, /Users/zhangyifan/IdeaProjects/hitao/src/main/java/com/qingtai/hitao/exception/, /Users/zhangyifan/IdeaProjects/hitao/src/main/java/com/qingtai/hitao/model/, /Users/zhangyifan/IdeaProjects/hitao/src/main/java/com/qingtai/hitao/provider/, /Users/zhangyifan/IdeaProjects/hitao/src/main/java/com/qingtai/hitao/service/, /Users/zhangyifan/IdeaProjects/hitao/src/main/java/com/qingtai/hitao/service/serviceimpl/]
6月 29, 2020 3:04:05 下午 io.github.yedaxia.apidocs.LogUtils info
信息: info: project type not set, try to figure out...
6月 29, 2020 3:04:05 下午 io.github.yedaxia.apidocs.LogUtils info
信息: info: start find controllers in path : /Users/zhangyifan/IdeaProjects/hitao/src/main/java/com/qingtai/hitao/advice/
6月 29, 2020 3:04:05 下午 io.github.yedaxia.apidocs.LogUtils info
信息: info: start find controllers in path : /Users/zhangyifan/IdeaProjects/hitao/src/main/java/com/qingtai/hitao/config/
6月 29, 2020 3:04:05 下午 io.github.yedaxia.apidocs.LogUtils info
信息: info: start find controllers in path : /Users/zhangyifan/IdeaProjects/hitao/src/main/java/com/qingtai/hitao/controller/
6月 29, 2020 3:04:05 下午 io.github.yedaxia.apidocs.LogUtils info
信息: info: find controller file : AdminController.java
6月 29, 2020 3:04:05 下午 io.github.yedaxia.apidocs.LogUtils info
信息: info: find controller file : IndexController.java
6月 29, 2020 3:04:05 下午 io.github.yedaxia.apidocs.LogUtils info
信息: info: find controller file : MessageController.java
6月 29, 2020 3:04:05 下午 io.github.yedaxia.apidocs.LogUtils info
信息: info: find controller file : CertificationController.java
6月 29, 2020 3:04:05 下午 io.github.yedaxia.apidocs.LogUtils info
信息: info: find controller file : AuthorizeController.java
6月 29, 2020 3:04:05 下午 io.github.yedaxia.apidocs.LogUtils info
信息: info: find controller file : CustomizeErrorController.java
6月 29, 2020 3:04:05 下午 io.github.yedaxia.apidocs.LogUtils info
信息: info: find controller file : UserController.java
6月 29, 2020 3:04:05 下午 io.github.yedaxia.apidocs.LogUtils info
信息: info: start find controllers in path : /Users/zhangyifan/IdeaProjects/hitao/src/main/java/com/qingtai/hitao/dao/
6月 29, 2020 3:04:06 下午 io.github.yedaxia.apidocs.LogUtils info
信息: info: start find controllers in path : /Users/zhangyifan/IdeaProjects/hitao/src/main/java/com/qingtai/hitao/dto/
6月 29, 2020 3:04:06 下午 io.github.yedaxia.apidocs.LogUtils info
信息: info: start find controllers in path : /Users/zhangyifan/IdeaProjects/hitao/src/main/java/com/qingtai/hitao/enums/
6月 29, 2020 3:04:06 下午 io.github.yedaxia.apidocs.LogUtils info
信息: info: start find controllers in path : /Users/zhangyifan/IdeaProjects/hitao/src/main/java/com/qingtai/hitao/exception/
6月 29, 2020 3:04:06 下午 io.github.yedaxia.apidocs.LogUtils info
信息: info: start find controllers in path : /Users/zhangyifan/IdeaProjects/hitao/src/main/java/com/qingtai/hitao/model/
6月 29, 2020 3:04:06 下午 io.github.yedaxia.apidocs.LogUtils info
信息: info: start find controllers in path : /Users/zhangyifan/IdeaProjects/hitao/src/main/java/com/qingtai/hitao/provider/
6月 29, 2020 3:04:06 下午 io.github.yedaxia.apidocs.LogUtils info
信息: info: start find controllers in path : /Users/zhangyifan/IdeaProjects/hitao/src/main/java/com/qingtai/hitao/service/
6月 29, 2020 3:04:06 下午 io.github.yedaxia.apidocs.LogUtils info
信息: info: start find controllers in path : /Users/zhangyifan/IdeaProjects/hitao/src/main/java/com/qingtai/hitao/service/serviceimpl/
6月 29, 2020 3:04:06 下午 io.github.yedaxia.apidocs.LogUtils info
信息: info: start to parse controller file : AdminController.java
Exception in thread "main" io.github.yedaxia.apidocs.exception.JavaFileNotFoundException: Cannot find java file , in java file : /Users/zhangyifan/IdeaProjects/hitao/src/main/java/com/qingtai/hitao/controller/AdminController.java, className : ResultDTO
	at io.github.yedaxia.apidocs.ParseUtils.searchJavaFile(ParseUtils.java:52)
	at io.github.yedaxia.apidocs.ParseUtils.parseClassNodeByType(ParseUtils.java:223)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.lambda$parseMethodDocs$7(AbsControllerParser.java:169)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1624)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.parseMethodDocs(AbsControllerParser.java:90)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.lambda$parse$0(AbsControllerParser.java:42)
	at java.base/java.util.Optional.ifPresent(Optional.java:176)
	at io.github.yedaxia.apidocs.parser.AbsControllerParser.parse(AbsControllerParser.java:39)
	at io.github.yedaxia.apidocs.doc.AbsDocGenerator.initControllerNodes(AbsDocGenerator.java:44)
	at io.github.yedaxia.apidocs.doc.AbsDocGenerator.<init>(AbsDocGenerator.java:27)
	at io.github.yedaxia.apidocs.doc.HtmlDocGenerator.<init>(HtmlDocGenerator.java:29)
	at io.github.yedaxia.apidocs.Docs.buildHtmlDocs(Docs.java:30)
	at com.qingtai.hitao.utils.Test.main(Test.java:29)
`

其中AdminController.java为
`

    @PostMapping("/sendSystemMessage")

    public ResultDTO<Integer> sendSystemMessage(@RequestParam("userId") Long userId, @RequestParam("content") String content) {

        int successNum = messageService.sendToAll(userId, content);

        return ResultDTO.successOf(successNum, GeneralResponseEnums.SUCCESS);

    }

`

ResultDTO.java为
`
@Data
public class ResultDTO<T> {
    private static final long serialVersionUID = 1L;
    private Boolean success;
    private T data;
    private Integer code;
    private String message;
`

然而它无法运行，我在其他的issue中也查看了相关问题，但是没能很好的解决我的问题，希望能得到您的帮助，非常感谢！

**Comment by xidianzyf** [comment]
我使用的是idea 2020版本

**Comment by xidianzyf** [comment]
我的环境是:
IntelliJ IDEA 2020.1.2 (Ultimate Edition)
macos 10.15.5
Java version "14.0.1" 2020-04-14 64-Bit
japidocs 1.4

**Comment by yangsongwei** [comment]
同样遇到了这个问题

**Comment by itheimahf** [comment]
我测试了一下， 如果把这个Result存放在当前工程中是可以运行的， 应该是找不到模块中的java文件

**Comment by linghxz** [comment]
放在依赖的jar包里面是不行的，什么时候可以支持？

**Comment by xidianzyf** [comment]
@itheimahf  能否看一下您的Result的结构，我也是放到了当前工程中，但还是无法运行。

**Comment by YeDaxia** [comment]
可以使用v1.4.1 ，在找不到源码的情况下回尝试使用反射的方式。
