### ISSUE TITLE
Exception in thread "main" java.lang.ClassCastException: com.github.javaparser.ast.type.WildcardType cannot be cast to com.github.javaparser.ast.type.ClassOrInterfaceType

### ISSUE THREAD

**Issue by YeDaxia** [YeDaxia/JApiDocs#57]
Exception in thread "main" java.lang.ClassCastException: com.github.javaparser.ast.type.WildcardType cannot be cast to com.github.javaparser.ast.type.ClassOrInterfaceType
报错。
Controler定义为：
![image](https://user-images.githubusercontent.com/7411134/86097131-cf37b380-bae6-11ea-8d42-d80e4654b8dc.png)

Result.java定义如下：
![image](https://user-images.githubusercontent.com/7411134/86096849-68b29580-bae6-11ea-9c9b-3131515164d8.png)

_Originally posted by @zhangyq1011 in https://github.com/YeDaxia/JApiDocs/issues/53#issuecomment-651604244_

**Comment by qnloft** [comment]
java.lang.ClassCastException: com.github.javaparser.ast.body.EnumDeclaration cannot be cast to com.github.javaparser.ast.body.ClassOrInterfaceDeclaration
