### ISSUE TITLE
生成结果乱码

### ISSUE THREAD

**Issue by ChristianZhou** [YeDaxia/JApiDocs#58]
![image](https://user-images.githubusercontent.com/35439368/86502960-9bf16f00-bddb-11ea-9d90-6499193b3793.png)

**Comment by YeDaxia** [comment]
开发环境问题~

**Comment by wangzhen99324** [comment]
IDEA 更改 VM options 即可解决

-Dfile.encoding=UTF-8

![image](https://user-images.githubusercontent.com/30686000/87267914-92fb4e80-c4fb-11ea-8394-e5ea29fc9cfc.png)
