### ISSUE TITLE
配置文件找不到： java.lang.NullPointerException

### ISSUE THREAD

**Issue by AjaxMa** [YeDaxia/JApiDocs#59]
D:\Develop\JDK\jdk-11.0.7\bin\java.exe "-javaagent:D:\Develop\IntelliJ IDEA 2020.1.1\lib\idea_rt.jar=51333:D:\Develop\IntelliJ IDEA 2020.1.1\bin" -Dfile.encoding=UTF-8 -classpath D:\Project\github\july\target\classes;D:\Develop\Maven\Repository\org\springframework\boot\spring-boot-starter-data-mongodb-reactive\2.3.1.RELEASE\spring-boot-starter-data-mongodb-reactive-2.3.1.RELEASE.jar;D:\Develop\Maven\Repository\org\springframework\boot\spring-boot-starter\2.3.1.RELEASE\spring-boot-starter-2.3.1.RELEASE.jar;D:\Develop\Maven\Repository\org\springframework\boot\spring-boot\2.3.1.RELEASE\spring-boot-2.3.1.RELEASE.jar;D:\Develop\Maven\Repository\org\springframework\boot\spring-boot-autoconfigure\2.3.1.RELEASE\spring-boot-autoconfigure-2.3.1.RELEASE.jar;D:\Develop\Maven\Repository\org\springframework\boot\spring-boot-starter-logging\2.3.1.RELEASE\spring-boot-starter-logging-2.3.1.RELEASE.jar;D:\Develop\Maven\Repository\ch\qos\logback\logback-classic\1.2.3\logback-classic-1.2.3.jar;D:\Develop\Maven\Repository\ch\qos\logback\logback-core\1.2.3\logback-core-1.2.3.jar;D:\Develop\Maven\Repository\org\apache\logging\log4j\log4j-to-slf4j\2.13.3\log4j-to-slf4j-2.13.3.jar;D:\Develop\Maven\Repository\org\apache\logging\log4j\log4j-api\2.13.3\log4j-api-2.13.3.jar;D:\Develop\Maven\Repository\org\slf4j\jul-to-slf4j\1.7.30\jul-to-slf4j-1.7.30.jar;D:\Develop\Maven\Repository\jakarta\annotation\jakarta.annotation-api\1.3.5\jakarta.annotation-api-1.3.5.jar;D:\Develop\Maven\Repository\org\yaml\snakeyaml\1.26\snakeyaml-1.26.jar;D:\Develop\Maven\Repository\io\projectreactor\reactor-core\3.3.6.RELEASE\reactor-core-3.3.6.RELEASE.jar;D:\Develop\Maven\Repository\org\reactivestreams\reactive-streams\1.0.3\reactive-streams-1.0.3.jar;D:\Develop\Maven\Repository\org\mongodb\mongodb-driver-reactivestreams\4.0.4\mongodb-driver-reactivestreams-4.0.4.jar;D:\Develop\Maven\Repository\org\mongodb\bson\4.0.4\bson-4.0.4.jar;D:\Develop\Maven\Repository\org\mongodb\mongodb-driver-core\4.0.4\mongodb-driver-core-4.0.4.jar;D:\Develop\Maven\Repository\org\springframework\data\spring-data-mongodb\3.0.1.RELEASE\spring-data-mongodb-3.0.1.RELEASE.jar;D:\Develop\Maven\Repository\org\springframework\spring-tx\5.2.7.RELEASE\spring-tx-5.2.7.RELEASE.jar;D:\Develop\Maven\Repository\org\springframework\spring-context\5.2.7.RELEASE\spring-context-5.2.7.RELEASE.jar;D:\Develop\Maven\Repository\org\springframework\spring-aop\5.2.7.RELEASE\spring-aop-5.2.7.RELEASE.jar;D:\Develop\Maven\Repository\org\springframework\spring-beans\5.2.7.RELEASE\spring-beans-5.2.7.RELEASE.jar;D:\Develop\Maven\Repository\org\springframework\spring-expression\5.2.7.RELEASE\spring-expression-5.2.7.RELEASE.jar;D:\Develop\Maven\Repository\org\springframework\data\spring-data-commons\2.3.1.RELEASE\spring-data-commons-2.3.1.RELEASE.jar;D:\Develop\Maven\Repository\org\slf4j\slf4j-api\1.7.30\slf4j-api-1.7.30.jar;D:\Develop\Maven\Repository\org\springframework\boot\spring-boot-starter-webflux\2.3.1.RELEASE\spring-boot-starter-webflux-2.3.1.RELEASE.jar;D:\Develop\Maven\Repository\org\springframework\boot\spring-boot-starter-json\2.3.1.RELEASE\spring-boot-starter-json-2.3.1.RELEASE.jar;D:\Develop\Maven\Repository\com\fasterxml\jackson\core\jackson-databind\2.11.0\jackson-databind-2.11.0.jar;D:\Develop\Maven\Repository\com\fasterxml\jackson\core\jackson-annotations\2.11.0\jackson-annotations-2.11.0.jar;D:\Develop\Maven\Repository\com\fasterxml\jackson\core\jackson-core\2.11.0\jackson-core-2.11.0.jar;D:\Develop\Maven\Repository\com\fasterxml\jackson\datatype\jackson-datatype-jdk8\2.11.0\jackson-datatype-jdk8-2.11.0.jar;D:\Develop\Maven\Repository\com\fasterxml\jackson\datatype\jackson-datatype-jsr310\2.11.0\jackson-datatype-jsr310-2.11.0.jar;D:\Develop\Maven\Repository\com\fasterxml\jackson\module\jackson-module-parameter-names\2.11.0\jackson-module-parameter-names-2.11.0.jar;D:\Develop\Maven\Repository\org\springframework\boot\spring-boot-starter-reactor-netty\2.3.1.RELEASE\spring-boot-starter-reactor-netty-2.3.1.RELEASE.jar;D:\Develop\Maven\Repository\io\projectreactor\netty\reactor-netty\0.9.8.RELEASE\reactor-netty-0.9.8.RELEASE.jar;D:\Develop\Maven\Repository\io\netty\netty-codec-http\4.1.50.Final\netty-codec-http-4.1.50.Final.jar;D:\Develop\Maven\Repository\io\netty\netty-common\4.1.50.Final\netty-common-4.1.50.Final.jar;D:\Develop\Maven\Repository\io\netty\netty-buffer\4.1.50.Final\netty-buffer-4.1.50.Final.jar;D:\Develop\Maven\Repository\io\netty\netty-transport\4.1.50.Final\netty-transport-4.1.50.Final.jar;D:\Develop\Maven\Repository\io\netty\netty-codec\4.1.50.Final\netty-codec-4.1.50.Final.jar;D:\Develop\Maven\Repository\io\netty\netty-codec-http2\4.1.50.Final\netty-codec-http2-4.1.50.Final.jar;D:\Develop\Maven\Repository\io\netty\netty-handler\4.1.50.Final\netty-handler-4.1.50.Final.jar;D:\Develop\Maven\Repository\io\netty\netty-resolver\4.1.50.Final\netty-resolver-4.1.50.Final.jar;D:\Develop\Maven\Repository\io\netty\netty-handler-proxy\4.1.50.Final\netty-handler-proxy-4.1.50.Final.jar;D:\Develop\Maven\Repository\io\netty\netty-codec-socks\4.1.50.Final\netty-codec-socks-4.1.50.Final.jar;D:\Develop\Maven\Repository\io\netty\netty-transport-native-epoll\4.1.50.Final\netty-transport-native-epoll-4.1.50.Final-linux-x86_64.jar;D:\Develop\Maven\Repository\io\netty\netty-transport-native-unix-common\4.1.50.Final\netty-transport-native-unix-common-4.1.50.Final.jar;D:\Develop\Maven\Repository\org\springframework\spring-web\5.2.7.RELEASE\spring-web-5.2.7.RELEASE.jar;D:\Develop\Maven\Repository\org\springframework\spring-webflux\5.2.7.RELEASE\spring-webflux-5.2.7.RELEASE.jar;D:\Develop\Maven\Repository\org\synchronoss\cloud\nio-multipart-parser\1.1.0\nio-multipart-parser-1.1.0.jar;D:\Develop\Maven\Repository\org\synchronoss\cloud\nio-stream-storage\1.1.3\nio-stream-storage-1.1.3.jar;D:\Develop\Maven\Repository\io\github\yedaxia\japidocs\1.4\japidocs-1.4.jar;D:\Develop\Maven\Repository\com\google\code\gson\gson\2.8.6\gson-2.8.6.jar;D:\Develop\Maven\Repository\com\github\javaparser\javaparser-core\3.6.16\javaparser-core-3.6.16.jar;D:\Develop\Maven\Repository\org\freemarker\freemarker\2.3.30\freemarker-2.3.30.jar;D:\Develop\Maven\Repository\org\projectlombok\lombok\1.18.12\lombok-1.18.12.jar;D:\Develop\Maven\Repository\org\springframework\spring-core\5.2.7.RELEASE\spring-core-5.2.7.RELEASE.jar;D:\Develop\Maven\Repository\org\springframework\spring-jcl\5.2.7.RELEASE\spring-jcl-5.2.7.RELEASE.jar cool.proj.july.docs.GenerateDocs
7月 06, 2020 4:40:27 下午 io.github.yedaxia.apidocs.LogUtils info
信息: info: find java src paths:  [D:\Project\github\july\src\main\java\]
7月 06, 2020 4:40:27 下午 io.github.yedaxia.apidocs.LogUtils info
信息: info: project type not set, try to figure out...
7月 06, 2020 4:40:27 下午 io.github.yedaxia.apidocs.LogUtils info
信息: info: start find controllers in path : D:\Project\github\july\src\main\java\
7月 06, 2020 4:40:27 下午 io.github.yedaxia.apidocs.LogUtils info
信息: info: find controller file : SystemController.java
7月 06, 2020 4:40:27 下午 io.github.yedaxia.apidocs.LogUtils info
信息: info: start to parse controller file : SystemController.java
7月 06, 2020 4:40:27 下午 io.github.yedaxia.apidocs.LogUtils info
信息: info: success to parse controller file : SystemController.java
7月 06, 2020 4:40:27 下午 io.github.yedaxia.apidocs.LogUtils info
信息: info: generate api docs start...
7月 06, 2020 4:40:27 下午 io.github.yedaxia.apidocs.LogUtils info
信息: info: start to generate docs for controller file : D:\Project\github\july\src\main\java\cool\proj\july\module\system\controller\SystemController.java
Exception in thread "main" java.lang.ExceptionInInitializerError
	at io.github.yedaxia.apidocs.doc.HtmlControllerDocBuilder.buildDoc(HtmlControllerDocBuilder.java:31)
	at io.github.yedaxia.apidocs.doc.AbsDocGenerator.generateControllersDocs(AbsDocGenerator.java:66)
	at io.github.yedaxia.apidocs.doc.AbsDocGenerator.generateDocs(AbsDocGenerator.java:35)
	at io.github.yedaxia.apidocs.Docs.buildHtmlDocs(Docs.java:32)
	at cool.proj.july.docs.GenerateDocs.main(GenerateDocs.java:20)
Caused by: java.lang.NullPointerException
	at java.base/java.io.Reader.<init>(Reader.java:167)
	at java.base/java.io.InputStreamReader.<init>(InputStreamReader.java:97)
	at io.github.yedaxia.apidocs.Utils.streamToString(Utils.java:90)
	at io.github.yedaxia.apidocs.codegenerator.TemplateProvider.provideTemplateForName(TemplateProvider.java:12)
	at io.github.yedaxia.apidocs.codegenerator.java.JavaTemplateProvider.provideTemplateForName(JavaTemplateProvider.java:13)
	at io.github.yedaxia.apidocs.codegenerator.java.JavaCodeGenerator.<clinit>(JavaCodeGenerator.java:34)
	... 5 more

Process finished with exit code 1

文件位置没有问题，

package cool.proj.july.module.system.controller;

import cool.proj.july.common.tool.api.R;
import lombok.AllArgsConstructor;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.bind.annotation.RestControllerAdvice;

/**
 * 系统接口
 *
 * @author Ajax.Ma
 * @version 1.0
 */
@RestControllerAdvice
@RestController
@RequestMapping("/api/v1/system")
@AllArgsConstructor
public class SystemController {

  /**
   * 获取系统时间
   *
   * @return
   */
  @GetMapping("/time")
  public R<String> time() {
    String res = System.currentTimeMillis() + "";
    return R.data(res);
  }
}

**Comment by yangsongwei** [comment]
同样遇到了这个问题，确实生成了api文档

**Comment by aohanhongzhi** [comment]
我的也是一样，貌似是模板文件没有找到
![](https://imgchr.com/i/U13RRf)

**Comment by YeDaxia** [comment]
这个问题是由于在jar里面的资源文件找不到导致的：

```java
Resources.class.getResourceAsStream("/" + fileName); //  fileName 对应resource 目录下的文件
```

经过几个童鞋在微信上的反馈，我初步以为是jdk 11 的问题，不过在mac上安装了 jdk 11.0.7 之后测试没发现异常，估计原因还要找一下；

另外下个版本也把资源路径的接口开放出来，如果实在不行，可以把模板文件拷贝出来，自己指定模板文件路径~

**Comment by YeDaxia** [comment]
这个问题这边始终不能复现，在1.4.1版本，这边提供了一个解决方法，具体如下：

第一步：把libaray下的[资源文件](https://github.com/YeDaxia/JApiDocs/tree/master/library/src/main/resources)拷贝一份到本机；

第二步，通过`setResourcePath`设定资源目录：

```
DocsConfig.setResourcePath
```
