### ISSUE TITLE
如何指定一个接口是否是新增/修改/过时,源码中有这个属性

### ISSUE THREAD

**Issue by authorXiao** [YeDaxia/JApiDocs#61]

**Comment by YeDaxia** [comment]
过时可以通过`@Deprecated`注解：

```java

    @Deprecated
    public void emailLogin(){

    }
```

代码的新增和修改，JApiDocs 会把上个版本的接口数据缓存起来，然后去检测和上个版本的区别。

![image](https://user-images.githubusercontent.com/4317015/87248600-dff40c00-c48c-11ea-947c-268d87e41d75.png)

**Comment by authorXiao** [comment]
我通过源码已经调试好了，谢谢------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;叶大侠&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月12日(星期天) 晚上10:13
收件人:&nbsp;&quot;YeDaxia/JApiDocs&quot;<JApiDocs@noreply.github.com&gt;;
抄送:&nbsp;&quot;肖习平&quot;<3171473639@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [YeDaxia/JApiDocs] 如何指定一个接口是否是新增/修改/过时,源码中有这个属性 (#61)

**Comment by wang7241** [comment]
> 
> 我通过源码已经调试好了，谢谢------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;叶大侠&quot;<notifications@github.com&gt; 发送时间:&nbsp;2020年7月12日(星期天) 晚上10:13 收件人:&nbsp;&quot;YeDaxia/JApiDocs&quot;<JApiDocs@noreply.github.com&gt;; 抄送:&nbsp;&quot;肖习平&quot;<3171473639@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;; 主题:&nbsp;Re: [YeDaxia/JApiDocs] 如何指定一个接口是否是新增/修改/过时,源码中有这个属性 (#61)

兄弟能否分享一下？
