### ISSUE TITLE
如果使用spring自带的ResponseEntity<xx>作为接口返回，JApiDocs无法识别。

### ISSUE THREAD

**Issue by xiangyangsanren** [YeDaxia/JApiDocs#62]
如果使用spring自带的ResponseEntity<xx>作为接口返回，JApiDocs无法识别，会抛出异常：Exception in thread "main" io.github.yedaxia.apidocs.exception.JavaFileNotFoundException: Cannot find java file , in java file 。
但是用自己封装的Result返回，就OK的。

**Comment by authorXiao** [comment]
或者继承第三方的java实体,JApiDocs无法识别

**Comment by YeDaxia** [comment]
1.4.1版本已支持ResponseEntity
