### ISSUE TITLE
生成了apidoc，但是没有内容，是空的

### ISSUE THREAD

**Issue by Jasyl0519** [YeDaxia/JApiDocs#63]
objc[71578]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_141.jdk/Contents/Home/bin/java (0x109f214c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_141.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x10af484e0). One of the two will be used. Which one is undefined.
七月 17, 2020 11:05:32 上午 io.github.yedaxia.apidocs.LogUtils info
信息: info: find multi modules in this project: [xxx-client, xxx-common, xxx-basic, xxx-component, xxx-start]
七月 17, 2020 11:05:33 上午 io.github.yedaxia.apidocs.LogUtils info
信息: info: find java src paths:  [/Users/jasonz/IdeaProjects/xxx/xxx-client/src/main/java/, /Users/jasonz/IdeaProjects/xxx/xxx-common/src/main/java/, /Users/jasonz/IdeaProjects/xxx/xxx-basic/src/main/java/, /Users/jasonz/IdeaProjects/xxx/xxx-component/src/main/java/, /Users/jasonz/IdeaProjects/xxx/xxx-start/src/test/java/]
七月 17, 2020 11:05:33 上午 io.github.yedaxia.apidocs.LogUtils info
信息: info: project type not set, try to figure out...
七月 17, 2020 11:05:34 上午 io.github.yedaxia.apidocs.LogUtils info
信息: info: start find controllers in path : /Users/jasonz/IdeaProjects/xxx/xxx-client/src/main/java/
七月 17, 2020 11:05:34 上午 io.github.yedaxia.apidocs.LogUtils info
信息: info: start find controllers in path : /Users/jasonz/IdeaProjects/xxx/xxx-common/src/main/java/
七月 17, 2020 11:05:34 上午 io.github.yedaxia.apidocs.LogUtils info
信息: info: start find controllers in path : /Users/jasonz/IdeaProjects/xxx/xxx-basic/src/main/java/
七月 17, 2020 11:05:34 上午 io.github.yedaxia.apidocs.LogUtils info
信息: info: start find controllers in path : /Users/jasonz/IdeaProjects/xxx/xxx-component/src/main/java/
七月 17, 2020 11:05:34 上午 io.github.yedaxia.apidocs.LogUtils info
信息: info: start find controllers in path : /Users/jasonz/IdeaProjects/xxx/xxx-start/src/test/java/
七月 17, 2020 11:05:34 上午 io.github.yedaxia.apidocs.LogUtils info
信息: info: generate api docs start...
七月 17, 2020 11:05:34 上午 io.github.yedaxia.apidocs.LogUtils info
信息: info: generate index start !!!
11:05:34.850 [main] DEBUG freemarker.cache - Couldn't find template in cache for "api-index.html.ftl"("zh_CN", UTF-8, parsed); will try to load it.
11:05:34.854 [main] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("api-index.html_zh_CN.ftl"): Not found
11:05:34.856 [main] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("api-index.html_zh.ftl"): Not found
11:05:34.857 [main] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("api-index.html.ftl"): Found
11:05:34.858 [main] DEBUG freemarker.cache - Loading template for "api-index.html.ftl"("zh_CN", UTF-8, parsed) from "jar:file:/Users/jasonz/.m2/repository/io/github/yedaxia/japidocs/1.4/japidocs-1.4.jar!/api-index.html.ftl"
11:05:35.024 [main] DEBUG freemarker.cache - Couldn't find template in cache for "api-common-catalog.html.ftl"("zh_CN", UTF-8, parsed); will try to load it.
11:05:35.025 [main] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("api-common-catalog.html_zh_CN.ftl"): Not found
11:05:35.025 [main] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("api-common-catalog.html_zh.ftl"): Not found
11:05:35.026 [main] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("api-common-catalog.html.ftl"): Found
11:05:35.026 [main] DEBUG freemarker.cache - Loading template for "api-common-catalog.html.ftl"("zh_CN", UTF-8, parsed) from "jar:file:/Users/jasonz/.m2/repository/io/github/yedaxia/japidocs/1.4/japidocs-1.4.jar!/api-common-catalog.html.ftl"
七月 17, 2020 11:05:35 上午 io.github.yedaxia.apidocs.LogUtils info
信息: info: generate index done !!!
七月 17, 2020 11:05:35 上午 io.github.yedaxia.apidocs.LogUtils info
信息: info: generate api docs done !!!
11:05:35.195 [main] DEBUG freemarker.cache - Couldn't find template in cache for "api-doc.md.ftl"("zh_CN", UTF-8, parsed); will try to load it.
11:05:35.196 [main] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("api-doc.md_zh_CN.ftl"): Not found
11:05:35.196 [main] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("api-doc.md_zh.ftl"): Not found
11:05:35.197 [main] DEBUG freemarker.cache - TemplateLoader.findTemplateSource("api-doc.md.ftl"): Found
11:05:35.197 [main] DEBUG freemarker.cache - Loading template for "api-doc.md.ftl"("zh_CN", UTF-8, parsed) from "jar:file:/Users/jasonz/.m2/repository/io/github/yedaxia/japidocs/1.4/japidocs-1.4.jar!/api-doc.md.ftl"

Process finished with exit code 0

**Comment by YeDaxia** [comment]
同 issue #59
