### ISSUE TITLE
参数没有详细区分

### ISSUE THREAD

**Issue by gjf450005950** [YeDaxia/JApiDocs#72]
示例
/**
     * 查询用户，附带分组数据
     *
     * @param id
     * @return
     */
    @GetMapping(value = "/admin/api/ua/user/{id}", params = {"group=true"})

文档仅生成id，未生成group=true，接口描述不完整

接口中3中参数可能同时存在：
URI，params，Body中

**Comment by YeDaxia** [comment]
你的完整方法名是什么？

声明到 `@param` 的参数，JApiDocs才会读取，然后对比方法中的参数，你可以参考如下：

```
/**
* 查询用户，附带分组数据
*
* @param id ID
* @param group 分组 
* @return
*/
public Hello(Long id, Integer group);
```

**Comment by gjf450005950** [comment]
/**
     * 查询用户，附带分组数据
     *
     * @param id
     * @return
     */
    @GetMapping(value = "/admin/api/ua/user/{id}", params = {"attachment=group"})
    public Result singleWithGroup(@PathVariable("id") Long id) {
        return Result.ok(service.findByIdWithGroup(id));
    }

是的，参数未加@param，参数附带在GetMapping内。

**Comment by YeDaxia** [comment]
暂不支持在@GetMapping 的 params 指定的参数，请在方法中进行声明。
