### ISSUE TITLE
枚举参数没有生成到文档里

### ISSUE THREAD

**Issue by gjf450005950** [YeDaxia/JApiDocs#74]
![image](https://user-images.githubusercontent.com/6262949/88495059-547d8d80-cfeb-11ea-902d-7bfdfbaeacef.png)

![image](https://user-images.githubusercontent.com/6262949/88495072-5e9f8c00-cfeb-11ea-8434-8d65a4bb935b.png)

**Comment by YeDaxia** [comment]
#73
