### ISSUE TITLE
枚举参数怎么生成到文档

### ISSUE THREAD

**Issue by sunshineAndWaterAsYou** [YeDaxia/JApiDocs#75]
![enumTest](https://user-images.githubusercontent.com/52561982/88555236-1cf9fa00-d05a-11ea-8e4c-611c371a127b.png)
![测试](https://user-images.githubusercontent.com/52561982/88555312-3602ab00-d05a-11ea-9506-6121f2d82f15.png)

**Comment by YeDaxia** [comment]
#74 #73
