### ISSUE TITLE
报错：com.github.javaparser.ast.type.VoidType cannot be cast to com.github.javaparser.ast.type.ClassOrInterfaceType

### ISSUE THREAD

**Issue by Fcscanf** [YeDaxia/JApiDocs#80]
com.github.javaparser.ast.type.VoidType cannot be cast to com.github.javaparser.ast.type.ClassOrInterfaceType
另外ApiResult无法导入，似乎找不到这个类
![image](https://user-images.githubusercontent.com/27654200/89121203-75644800-d4ef-11ea-8d07-101b1e430cfe.png)

**Comment by XswSavage** [comment]
一样的问题

**Comment by XswSavage** [comment]
com.github.javaparser.ast.type.WildcardType cannot be cast to com.github.javaparser.ast.type.ClassOrInterfaceType

**Comment by YeDaxia** [comment]
这是由于接口方法没有声明返回参数导致的(void)，理论上请求应该都有返回值。如果没有通过return type来声明的，可以通过@ApiDoc来指定返回类型。

例子：

```
@ApiDoc(Result.class)
public void hello()
```

**Comment by XswSavage** [comment]
那大佬，他这个WildcardType 是什么问题呢

**Comment by YeDaxia** [comment]
#90
