### ISSUE TITLE
请问返回值是Map类型，如何在文档中生成各个key的说明

### ISSUE THREAD

**Issue by wmmhnsz** [YeDaxia/JApiDocs#84]
请问返回值是Map类型，如何在文档中生成各个key的说明
比如：
{
  code:200,
  msg:"成功",
  data:{
     person:{
        name:"张三"
     },
     phone:{
       name:"苹果"
     }
  }
}

使用Map的方式，要生成data下面的person和phone的说明，如果每次都包装成bean的话，有点麻烦

**Comment by wuweidi** [comment]
这个想法其实有点矛盾
既然是map，各个key应该是在代码中动态添加的。
如果能确定返回对象的字段，何不定义成一个实体类呢，可读性也会好一些。

**Comment by wmmhnsz** [comment]
首先感谢您在百忙之中的回复
我的想法是这样：
可否通过某个注解明确表明map中的key对应的value（实际是类型，比如String,Long,或实体类），这样在往前端返回数据的时候，具体返回多少个数据，可以自由添加，而不用每次返回信息的时候，都要去先定义一个实体类，例如：
@ApiMap(
    key={"name","age","user"},
    type={String.class,String.class,User.class},
    notes={"姓名","年龄","用户信息"}
    )
public ApiResult<Map<String,Object>> getUser(){
    Map map = new HashMap();
    map.put("name","张三");
    map.put("age","18");
    User user = new User();
    map.put("user",user);
    return ApiResult.ok().addData(map);
}

然后生成文档的时候，依次解析@ApiMap注解中的key（key值），type（数据类型），notes（数据注释），如果type中包含有实体类的话，就深入解析实体类的属性注释。

返回到前段的json数据格式：
{
    code:"//响应码",
    msg:"//信息",
    data:{
        name:"//姓名",
        age:"//年龄",
        user:{//用户信息，下面的信息对应User实体类的各个属性
            birthday:"//生日",
            sex:"//性别"
        }
    }
}
这样的话，如果想要增加返回信息的话，只需要继续map.put()就可以了，而且，最重要的是，也不需要每个接口方法都定义一个返回的实体类。

有的时候，接口只需要返回一个信息，比如
data{
    name:"张三"
}



wmmhnsz@163.com
 
发件人： D
发送时间： 2020-08-13 15:03
收件人： YeDaxia/JApiDocs
抄送： wmmhnsz; Author
主题： Re: [YeDaxia/JApiDocs] 请问返回值是Map类型，如何在文档中生成各个key的说明 (#84)
这个想法其实有点矛盾
既然是map，各个key应该是在代码中动态添加的。
如果能确定返回对象的字段，何不定义成一个实体类呢，可读性也会好一些。

**Comment by wuweidi** [comment]
这个实现方式肯定是没问题的，比如mybatis的注解似乎也有类似的思路。
但反过来想，如果实现了你说的效果，实际接口的入参出参结构其实就不重要了，因为一个注解里面都能定义所有的字段。
那么问题来了，这样就得维护两套结构，注解里面定义的结构和接口实际的参数结构，并且得保证它们没有差异才有意义，You know，只要是人为操作就可能会出现差异；而用实体类的话，就只需要关注接口的参数接口就行了，变动一处，其他地方都跟着变，这不就是我们程序员喜欢的方式嘛。
所以，还是那句话，确定的结构，就用实体类定义吧，不确定的才用Map，这种规范带来的好处，也不仅限于此的。

**Comment by wmmhnsz** [comment]
哈哈，确实，有利就有弊嘛，毕竟我们还是要面向对象的，对我而言，使用map的地方倒是不多，map说明的注解，也只是增加生成接口文档的一种注解方式而已。



wmmhnsz@163.com
 
发件人： D
发送时间： 2020-08-13 16:22
收件人： YeDaxia/JApiDocs
抄送： wmmhnsz; Author
主题： Re: [YeDaxia/JApiDocs] 请问返回值是Map类型，如何在文档中生成各个key的说明 (#84)
这个实现方式肯定是没问题的，比如mybatis的注解似乎也有类似的思路。
但反过来想，如果实现了你说的效果，实际接口的入参出参结构其实就不重要了，因为一个注解里面都能定义所有的字段。
那么问题来了，这样就得维护两套结构，注解里面定义的结构和接口实际的参数结构，并且得保证它们没有差异才有意义，You know，只要是人为操作就可能会出现差异；而用实体类的话，就只需要关注接口的参数接口就行了，变动一处，其他地方都跟着变，这不就是我们程序员喜欢的方式嘛。
所以，还是那句话，确定的结构，就用实体类定义吧，不确定的才用Map，这种规范带来的好处，也不仅限于此的。

**Comment by YeDaxia** [comment]
1.4.3 在@ApiDoc 添加了stringResult 返回字符串，详细参考中文文档@ApiDoc 部分~
