### ISSUE TITLE
Controller类的注释无法显示

### ISSUE THREAD

**Issue by coderzhw** [YeDaxia/JApiDocs#88]
我的代码如下：
![image](https://user-images.githubusercontent.com/10148784/89968881-9f540200-dc87-11ea-91ec-fe8bdcd83eb9.png)

生成的截图如下图：
![image](https://user-images.githubusercontent.com/10148784/89968770-4be1b400-dc87-11ea-823b-3985cfede4a0.png)
为什么还是显示UserController而不是用户接口？

**Comment by YeDaxia** [comment]
注释测试正常，请参考SpringDemo~
