### ISSUE TITLE
不支持@PathVariable检测？

### ISSUE THREAD

**Issue by MisterWhoDevelopers** [YeDaxia/JApiDocs#9]

**Comment by MisterWhoDevelopers** [comment]
![qq 20180308115805](https://user-images.githubusercontent.com/24573712/37132294-18a05de2-22c8-11e8-97a5-2e6b2a4cee01.png)
![qq 20180308115828](https://user-images.githubusercontent.com/24573712/37132296-18d3d1a4-22c8-11e8-95ce-2d01c45f6383.png)

**Comment by YeDaxia** [comment]
谢谢反馈，已经改过来了～
