### ISSUE TITLE
支持@PathVariable+@RequestBody组合吗

### ISSUE THREAD

**Issue by LongylG** [YeDaxia/JApiDocs#92]
当@PathVariable和@RequestBody同时存在时，PathVariable未在文档中展示，只有返回结果。定义的接口方法如下：
@PostMapping("/{id}")
public Result updateShippingAddress(@PathVariable Long id, @Valid @RequestBody ShippingAddressDto shippingAddressDto)

**Comment by YeDaxia** [comment]
1.4.3 已修复该问题
